# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voLXgOD886Vis_Mr-hTO2tNCHhCwDSSU
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

# --- DATA CLEANING ---
# Load the dataset. Make sure the filename is correct.
df = pd.read_csv('student_performance_prediction.csv')

# Handling missing values
# For numerical columns, fill with the mean value
df['Study Hours per Week'].fillna(df['Study Hours per Week'].mean(), inplace=True)
df['Attendance Rate'].fillna(df['Attendance Rate'].mean(), inplace=True)

# For categorical columns, fill with 'Unknown'
df['Passed'].fillna('Unknown', inplace=True)
df['Parent Education Level'].fillna('Unknown', inplace=True)

# For 'Previous Grades', fill with the most common value (mode)
df['Previous Grades'].fillna(df['Previous Grades'].mode()[0], inplace=True)

# For 'Participation in Extracurricular Activities', fill with 'Unknown'
df['Participation in Extracurricular Activities'].fillna('Unknown', inplace=True)

# --- DATA TRANSFORMATION ---
# Initialize the LabelEncoder for ordinal features like 'Parent Education Level'
le = LabelEncoder()

# Encode 'Parent Education Level' (categories to numbers)
df['Parent Education Level'] = le.fit_transform(df['Parent Education Level'])

# Apply One-Hot Encoding to categorical columns like 'Previous Grades', 'Passed',
# and 'Participation in Extracurricular Activities' using pd.get_dummies().
df = pd.get_dummies(df, columns=['Previous Grades', 'Passed', 'Participation in Extracurricular Activities'], prefix=['Grade', 'Passed', 'Activity'], dtype=int)

# Print columns to verify transformation
#print(df.columns)

# ------data
# CORRELATION HEATMAP (Fix applied here)
# First 1000 rows, only numeric columns, annot=False for clearer plot
df_sample = df.head(1000)
corr = df_sample.select_dtypes(include=['number']).corr()

#print(corr)
# Print the column names of the DataFrame
print(df.columns)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

# LOAD AND CLEAN DATA (Using standard name 'df')
df = pd.read_csv('student_performance_prediction.csv')

# Handling missing values
df['Study Hours per Week'].fillna(df['Study Hours per Week'].mean(), inplace=True)
df['Attendance Rate'].fillna(df['Attendance Rate'].mean(), inplace=True)
df['Passed'].fillna('Unknown', inplace=True)
df['Parent Education Level'].fillna('Unknown', inplace=True)
df['Previous Grades'].fillna(df['Previous Grades'].mode()[0], inplace=True)
df['Participation in Extracurricular Activities'].fillna('Unknown', inplace=True)

# DATA TRANSFORMATION
le = LabelEncoder()
df['Parent Education Level_Enc'] = le.fit_transform(df['Parent Education Level'])
df['Previous Grades_Enc'] = le.fit_transform(df['Previous Grades'])

# Select the FOUR columns for histogram from first 1000 rows
# We use the encoded versions for categorical data
columns_to_plot = ['Study Hours per Week', 'Attendance Rate', 'Previous Grades_Enc', 'Parent Education Level_Enc']
df_sample = df.head(1000)

# Generate histograms
df_sample[columns_to_plot].hist(bins=15, figsize=(15, 10), layout=(2, 2))
plt.suptitle('Data Distribution for Core Features')
plt.show()

# Print original labels for reference
print("Encoded 'Previous Grades' Labels:")
print(dict(zip(le.classes_, range(len(le.classes_)))))

# Need to refit label encoder for 'Parent Education Level' to show its original labels
le.fit(df['Parent Education Level'])
print("\nEncoded 'Parent Education Level' Labels:")
print(dict(zip(le.classes_, range(len(le.classes_)))))

print(df.columns)
print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# List of columns to drop because they are either IDs,
# the target variable itself, or non-numeric text strings.
drop_cols = [
    'Student ID',
    'Passed',
    'Parent Education Level',
    'Previous Grades',
    'Participation in Extracurricular Activities'
]

# X contains the features (independent variables)
X = df.drop(drop_cols, axis=1)

# y contains the target (the outcome we want to predict)
y = df['Passed']

# Splitting the dataset into Training set (80%) and Testing set (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Logistic Regression model
# max_iter is increased to ensure the model converges
model = LogisticRegression(max_iter=1000)

# Train the model using the training data
model.fit(X_train, y_train)

# Use the trained model to make predictions on the test data
y_pred = model.predict(X_test)

# Print the final results
print(f"Accuracy Score: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import pandas as pd

# The feature names MUST match the training columns exactly.
# Based on your screenshot, it should be 'Study Hours per Week'
new_student = pd.DataFrame({
    'Study Hours per Week': [25],
    'Attendance Rate': [90],
    'Parent Education Level_Enc': [2],
    'Previous Grades_Enc': [3]
})

# Make the prediction
prediction = model.predict(new_student)

# 1 usually means 'Pass', 0 means 'Fail'
result = "Pass" if prediction[0] == 1 else "Fail"

print(f"The model predicts the student will: {result}")

import pickle

# Corrected Save Code
# The first argument is the 'model' object, the second is the 'model_file'
with open('student_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

print("Model saved successfully as 'student_model.pkl'")

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. Calculate Logistic Regression Accuracy (re-defining 'accuracy')
y_pred_lr = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lr)

# 2. Initialize and Train the Decision Tree Model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# 3. Predict and Calculate Decision Tree Accuracy
dt_y_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_y_pred)

# 4. Final Comparison Output
print(f"Logistic Regression Accuracy: {accuracy:.2f}")
print(f"Decision Tree Accuracy: {dt_accuracy:.2f}")

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# We set max_depth=2 so the diagram is small, clear, and fast to load
plt.figure(figsize=(12, 8))

plot_tree(dt_model,
          feature_names=X.columns,
          filled=True,
          rounded=True,
          max_depth=2,
          fontsize=10)

plt.title("Simplified Decision Tree Logic")
plt.show()

import pandas as pd

# This helps you see which feature is the 'King' of your dataset
importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': dt_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("Top Factors for Student Success:")
print(importance_df)

def predict_student_status(study_hours, attendance, parent_edu, prev_grades):
    """
    Function to predict if a student will Pass or Fail.
    Inputs:
    - study_hours (Numeric)
    - attendance (Numeric 0-100)
    - parent_edu (Encoded Number)
    - prev_grades (Encoded Number)
    """
    # Creating the input dataframe exactly like our training data
    data = pd.DataFrame({
        'Study Hours per Week': [study_hours],
        'Attendance Rate': [attendance],
        'Parent Education Level_Enc': [parent_edu],
        'Previous Grades_Enc': [prev_grades]
    })

    # Using the Decision Tree model for prediction
    prediction = dt_model.predict(data)

    if prediction[0] == 1:
        return "CONGRATULATIONS: The student is predicted to PASS."
    else:
        return "WARNING: The student is predicted to FAIL. Needs intervention."

# --- TEST IT HERE ---
# Example: 30 hours study, 90% attendance, etc.
print(predict_student_status(30, 90, 2, 3))